# Generated by Django 2.0 on 2019-04-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cardHpt',
        ),
    ]
