# Generated by Django 2.0 on 2019-04-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_auto_20190407_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parent/photo')),
                ('sex', models.BooleanField(choices=[(True, 'male'), (False, 'female')], default=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='s_parent', to='students.Student')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('id', 'student')},
        ),
    ]
