# Generated by Django 2.0 on 2019-04-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': '家长', 'verbose_name_plural': '家长'},
        ),
    ]
